version: "3.9"
services:
  frontend:
      container_name: frontend
      build:
        context: .
        dockerfile: ./settings/DockerfileFrontend
      volumes:
      - type: bind
        source: ./frontend
        target: /frontend
      ports:
        - 3000:3000
      tty: true
  #backend:
  #  container_name: backend
  #  build:
  #    context: .
  #    dockerfile: ./settings/DockerfileBackend
  #  ports:
  #    - 80:80
